FROM wso2/micro-integrator:latest
COPY CompositeApps/*.car /home/wso2carbon/wso2mi/repository/deployment/server/carbonapps/
#COPY Libs/*.jar /home/wso2carbon/wso2mi/lib/
#COPY Conf/* /home/wso2carbon/wso2mi/conf/